<a href="https://colab.research.google.com/github/jorrodriguezco/MetNumUN2022I/blob/main/jorrodriguezco_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
%matplotlib inline

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [6]:
assert ran_the_first_cell, "Oh noes!"

In [7]:
assert ran_the_first_cell, "Oh no!"

In [8]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [9]:
x = [10, 'dos', 7.0, 3, 5.3, "seis"]
x

[10, 'dos', 7.0, 3, 5.3, 'seis']

In [10]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [11]:
# Lists can be indexed like C-style arrays.
primero = x[0]
segundo = x[1]
print("primero:", primero)
print("segundo:", segundo)

primero: 10
segundo: dos


In [12]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [13]:
ultimo = x[-1]
penultimo = x[-2]
print("ulmtimo:", ultimo)
print("pemnultimo:", penultimo)

ulmtimo: seis
pemnultimo: 5.3


In [14]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [15]:
sublist = x[2:4]
sublist

[7.0, 3]

In [16]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [17]:
# l[:N] is equivalent to l[0:N].
primeros_tres = x[:3]
primeros_tres

[10, 'dos', 7.0]

In [18]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [19]:
despues_del_tres= x[3:]
despues_del_tres

[3, 5.3, 'seis']

In [20]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [21]:
xd=['i','j','k','l','m','n','o','p','q','r','s']

In [22]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [23]:
xd[::-1]

['s', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i']

In [24]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [25]:
xd = [10, 9, 8, 7, 6]
print("antes:", xd)
xd.append('seis')
print("antes:", xd)

antes: [10, 9, 8, 7, 6]
antes: [10, 9, 8, 7, 6, 'seis']


In [26]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

In [27]:
xd = [3, 6, 9, 12, 15]
[i * 2 for i in xd]

[6, 12, 18, 24, 30]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [28]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

In [29]:
futbolistas = {'radamel': 'falcao', 'leonel': 'messi', 'fernando': 'uribe'}
futbolistas

{'fernando': 'uribe', 'leonel': 'messi', 'radamel': 'falcao'}

In [30]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

In [31]:
futbolistas['diego']='maradona'
futbolistas

{'diego': 'maradona',
 'fernando': 'uribe',
 'leonel': 'messi',
 'radamel': 'falcao'}

In [32]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

In [33]:
del futbolistas['diego']
futbolistas

{'fernando': 'uribe', 'leonel': 'messi', 'radamel': 'falcao'}

In [34]:
# No slicing.
philosophers['Bertrand']

'Russell'

In [35]:
# No slicing.
futbolistas['leonel']

'messi'

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [36]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [37]:
x=[[9,8,7],[6,5,4],[3,2,1]]
d=[[1,3,5,7],[2,4,6,8]]

In [38]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

In [39]:
def matmul2(A, B):
    """Multiply matrix A by matrix B."""
    filas = len(A)
    columnas = len(B[0])
    out = [[0 for col in range(columnas)] for row in range(filas)]
    
    for i in range(filas):
        for j in range(columnas):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

In [40]:
%%time

matmul(a, b)

CPU times: user 43 µs, sys: 7 µs, total: 50 µs
Wall time: 61.8 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [41]:
%%time

matmul2(x, d)

CPU times: user 29 µs, sys: 5 µs, total: 34 µs
Wall time: 38.9 µs


[[25, 59, 93, 127], [16, 38, 60, 82], [7, 17, 27, 37]]

In [42]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.5738142984560038, 0.8078195875668653, 0.9109704308703671],
 [0.8046511639031221, 0.801635194632018, 0.9498497574842492]]

In [43]:
import random
def random_matrix2(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm2 = random_matrix2(4, 5)
randm2

[[0.5973305521848764,
  0.056441018265259046,
  0.24323140676787525,
  0.5972485812206394,
  0.6963029812231863],
 [0.2452827421253495,
  0.8698836571950008,
  0.016552714653273792,
  0.15569300505168826,
  0.6209149238258335],
 [0.5828535763869283,
  0.7717217932929925,
  0.7913449683484194,
  0.29276958739967807,
  0.45680732195865326],
 [0.8217873431031779,
  0.7585019949988908,
  0.7677727815203977,
  0.8537365995076391,
  0.30994092397486783]]

In [44]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 12 s, sys: 72.8 ms, total: 12.1 s
Wall time: 13.3 s


In [45]:
%%time
randa1 = random_matrix(455, 166)
randb2 = random_matrix(166, 455)
x = matmul(randa, randb)

CPU times: user 11.3 s, sys: 45.8 ms, total: 11.3 s
Wall time: 11.3 s


In [46]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [47]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xd, yd):
    return sum(x * y for x, y in zip(xd, yd))

In [49]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

UsageError: Cell magic `%%fortran` not found.


In [ ]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [ ]:
%%time
python_dot_product(list_data, list_data)

In [ ]:
%%time
fortran_dot_product(array_data, array_data)

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [50]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [51]:
# Dynamic typing.
def sum_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([16, 21, 23, 14], [10, 21 + 0j, 3.6, 'four'])
#[type(x) for x in _]

[160,
 (441+0j),
 82.8,
 'fourfourfourfourfourfourfourfourfourfourfourfourfourfour']

In [52]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


In [53]:
# Interpretation overhead.
source_code = 'b + c * a'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (b)
              2 LOAD_NAME                1 (c)
              4 LOAD_NAME                2 (a)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [54]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [55]:
import numpy as np

datos = np.array([5, 6, 7, 8])
data

array([1, 2, 3, 4])

In [56]:
data + data

array([2, 4, 6, 8])

In [57]:
datos+datos

array([10, 12, 14, 16])

In [58]:
%%time
# Naive dot product
(data* data).sum()

CPU times: user 83 µs, sys: 2 µs, total: 85 µs
Wall time: 90.6 µs


30

In [59]:
%%time
# Naive dot product
(datos * datos).sum()

CPU times: user 61 µs, sys: 2 µs, total: 63 µs
Wall time: 68.7 µs


174

In [60]:
%%time
# Built-in dot product.
data.dot(data)

CPU times: user 43 µs, sys: 1 µs, total: 44 µs
Wall time: 49.6 µs


30

In [61]:
%%time
# Built-in dot product.
datos.dot(datos)

CPU times: user 27 µs, sys: 1 µs, total: 28 µs
Wall time: 31.9 µs


174

In [66]:
%%time
fortran_dot_product(array_data, array_data)

NameError: ignored

In [63]:
# Numpy won't allow us to write a string into an int array.
data[0] = "foo"

ValueError: ignored

In [64]:
# Numpy won't allow us to write a string into an int array.
datos[0] = "xdd"

ValueError: ignored

In [65]:
# We also can't grow an array once it's created.
data.append(3)

AttributeError: ignored

In [67]:
datos.append(47)

AttributeError: ignored

In [68]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

In [69]:
tres_por_tres = datos.reshape(2, 2)
tres_por_tres

array([[5, 6],
       [7, 8]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


In [71]:
arr = np.array([7, 6, 5, 4, 3, 2], dtype='int16').reshape(2, 3)
print("arreglo:\n", arr, sep='')
print("===========")
print("tipo:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

arreglo:
[[7 6 5]
 [4 3 2]]
tipo: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x07\x00\x06\x00\x05\x00\x04\x00\x03\x00\x02\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [72]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [74]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [75]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [76]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [77]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [78]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [79]:
senos = np.sin(np.linspace(0, 3.20, 9))
cosenos = np.cos(np.linspace(0, 3.20, 8))
senos

array([ 0.        ,  0.38941834,  0.71735609,  0.93203909,  0.9995736 ,
        0.90929743,  0.67546318,  0.33498815, -0.05837414])

In [80]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [81]:
senos[6]

0.6754631805511506

In [82]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

In [83]:
senos[:4]  # First four elements  

array([0.        , 0.38941834, 0.71735609, 0.93203909])

In [84]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [85]:
senos[6:]  # Elements from 6 on.

array([ 0.67546318,  0.33498815, -0.05837414])

In [86]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [87]:
senos[::2]  # Every other element.

array([ 0.        ,  0.71735609,  0.9995736 ,  0.67546318, -0.05837414])

In [88]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [89]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", senos)
print("sines > 0.5:\n", senos > 0.5)
print("sines[sines > 0.5]:\n", senos[senos > 0.5])

sines:
 [ 0.          0.38941834  0.71735609  0.93203909  0.9995736   0.90929743
  0.67546318  0.33498815 -0.05837414]
sines > 0.5:
 [False False  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.71735609 0.93203909 0.9995736  0.90929743 0.67546318]


In [90]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [91]:
# We index with lists/arrays of integers to select values at those indices.
print(senos)
senos[[0, 3, 6]]

[ 0.          0.38941834  0.71735609  0.93203909  0.9995736   0.90929743
  0.67546318  0.33498815 -0.05837414]


array([0.        , 0.93203909, 0.67546318])

In [92]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [93]:
datos_d = np.array([3, 6, 5, 16, -4, 8, 5])

In [94]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [95]:
sort_indices2 = np.argsort(datos_d)
sort_indices2

array([4, 0, 2, 6, 1, 5, 3])

In [96]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [97]:
datos_d[sort_indices2]

array([-4,  3,  5,  5,  6,  8, 16])

In [98]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [99]:
mercado = np.array([3, 6, 5, 16, -4, 8, 5])  # Presumably in dollars?
sets = np.array(['A', 'B', 'C', 'D', 'E','F','G'])

In [100]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [101]:
sort_by_mcap = np.argsort(mercado)
sets[sort_by_mcap]

array(['E', 'A', 'C', 'G', 'B', 'F', 'D'], dtype='<U1')

In [102]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [103]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [104]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
data2 = np.arange(20).reshape(4, 5)
data2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [106]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [107]:
data2[:4, :2]  # First two rows and first two columns.

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [108]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [109]:
data2[:3, [0, -1]]  

array([[ 0,  4],
       [ 5,  9],
       [10, 14]])

In [110]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [111]:
data2[(data2[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [135]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [138]:
def varianza(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [136]:
variance(np.random.standard_normal(1000))

0.9994191308881305

In [139]:
varianza(np.random.standard_normal(1000))

0.9481558319954977

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [114]:
data = np.arange(30)
data.mean()

14.5

In [140]:
datos=np.arange(35)
datos.mean()

17.0

- ...but we can do more interesting things with multi-dimensional arrays.

In [115]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [143]:
datos = np.arange(36).reshape(3, 12)
datos

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [144]:
data.mean()

14.5

In [145]:
datos.mean()

17.5

In [117]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [146]:
datos.mean(axis=0)

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [118]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

In [147]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [119]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [148]:
filas = np.array([5, 6, 7, 8,9])
columnas = np.array([[1], [2], [3]])
print("fila:\n", filas, sep='')
print("columna:\n", columnas, sep='')

fila:
[5 6 7 8 9]
columna:
[[1]
 [2]
 [3]]


In [120]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [149]:
filas + columnas

array([[ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 12]])

<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [150]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


In [151]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Datos:\n", datos, sep='')
print("Promedio:\n", datos.mean(axis=0), sep='')
print("Datos - Promedio:\n", datos - datos.mean(axis=0), sep='')

Datos:
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]]
Promedio:
[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]
Datos - Promedio:
[[-12. -12. -12. -12. -12. -12. -12. -12. -12. -12. -12. -12.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 12.  12.  12.  12.  12.  12.  12.  12.  12.  12.  12.  12.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [154]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [155]:
x = pd.Series(index=['f', 'g', 'h', 'i', 'j','k'], data=[1, 2, 3, 4, 5,6])
x

f    1
g    2
h    3
i    4
j    5
k    6
dtype: int64

In [156]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [157]:
# There are two pieces to a Series: the index and the values.
print("El indice es:", x.index)
print("The values are:", x.values)

El indice es: Index(['f', 'g', 'h', 'i', 'j', 'k'], dtype='object')
The values are: [1 2 3 4 5 6]


In [124]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [158]:
# We can look up values out of a Series by position...
x.iloc[0]

1

In [159]:
# ... or by label.
s.loc['a']

1

In [161]:
# ... or by label.
x.loc['f']

1

In [162]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [163]:
# Slicing works as expected...
x.iloc[:2]

f    1
g    2
dtype: int64

In [164]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [166]:
# ...but it works with labels too!
x.loc[:'g']

f    1
g    2
dtype: int64

In [167]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [168]:
# Fancy indexing works the same as in numpy.
x.iloc[[1, 3]]

g    2
i    4
dtype: int64

In [169]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [170]:
# As does boolean masking.
x.loc[x > 3]

i    4
j    5
k    6
dtype: int64

In [171]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [174]:
# Element-wise operations are aligned by index.
other_x = pd.Series({'w': 35.0, 'a': 70.0, 'm': 34.0, 'd': 50.0})
other_x

w    35.0
a    70.0
m    34.0
d    50.0
dtype: float64

In [172]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [175]:
x + other_x

a   NaN
d   NaN
f   NaN
g   NaN
h   NaN
i   NaN
j   NaN
k   NaN
m   NaN
w   NaN
dtype: float64

In [176]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [177]:
(x + other_x).fillna(0.0)

a    0.0
d    0.0
f    0.0
g    0.0
h    0.0
i    0.0
j    0.0
k    0.0
m    0.0
w    0.0
dtype: float64

In [178]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

FileNotFoundError: ignored

In [179]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

NameError: ignored

In [180]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

NameError: ignored

# Rolling Operations

<center><img src="images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [181]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

NameError: ignored

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [182]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

NameError: ignored

# "Real World" Data

In [183]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

ModuleNotFoundError: ignored

In [184]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

NameError: ignored

In [185]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

NameError: ignored

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [186]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

NameError: ignored

In [187]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

NameError: ignored

In [188]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

NameError: ignored

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!